language: rust
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libssl-dev

cache: cargo
rust:
  - nightly

before_cache: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin

script:
  - cargo +nightly clean
  - cargo +nightly build
  - cargo +nightly test

after_success: |
  cargo +nighlty tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
