pool:
  vmImage: "vs2017-win2016"

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain %channel% --default-host %target%
  displayName: 'Setup Rust'
- script: |
    set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    cargo test -v
  displayName: 'cargo test'

strategy:
  maxParallel: 4
  matrix:
    msvc:
      channel: beta
      target: x86_64-pc-windows-msvc
    gnu:
      channel: beta
      target: x86_64-pc-windows-gnu
