[package]
name = "llvmenv"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
log = "*"
toml = "*"
failure = "*"
serde = "1"
serde_derive = "1"
itertools = "*"
derive-new = "*"
structopt = "*"
