[package]
name = "llvmenv"
version = "0.1.6"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description   = "Manage LLVM/Clang builds"
documentation = "https://docs.rs/llvmenv"
repository    = "https://github.com/termoshtt/llvmenv"
keywords      = ["env", "llvm", "clang"]
license       = "MIT"
readme        = "README.md"
categories    = []

[dependencies]
env_logger = "0.5"
failure = "0.1"
glob = "0.2"
itertools = "0.7"
log = "0.4"
num_cpus = "1"
serde = "1"
serde_derive = "1"
structopt = "0.2"
toml = "0.4"
reqwest = "0.8"
tempfile= "3"
