[package]
name = "llvmenv"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
derive-new = "0.5"
failure = "0.1"
glob = "0.2"
itertools = "0.7"
log = "0.4"
num_cpus = "1"
serde = "1"
serde_derive = "1"
structopt = "0.2"
toml = "0.4"
