version: 2
jobs:
  test:
    docker:
      - image: rust:1.25
    steps:
      - checkout
      - run:
          name: cargo test
          command: |
            cargo test
  check_init:
    docker:
      - image: rust:1.25
    steps:
      - checkout
      - run:
          name: check init toml
          command: |
            cargo run init
            cargo run entries

workflows:
  version: 2
  tests:
    jobs:
      - test
      - check_init
