version: 2
jobs:
  cargo_test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: cargo test
          command: |
            cargo test
  run_entries:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: run init/entries
          command: |
            cargo run init
            cargo run entries

workflows:
  version: 2
  tests:
    jobs:
      - cargo_test
      - run_entries
