version: 2
jobs:
  cargo_test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: cargo test
          command: |
            cargo test
  run_entries:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: check init toml
          command: |
            cargo run init
            cargo run entries
  run_build_entry:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Test building LLVM
          command: |
            cargo run -- init
            cargo run -- build-entry llvm-mirror

workflows:
  version: 2
  tests:
    jobs:
      - cargo_test
      - run_entries
      - run_build_entry:
          requires:
            - cargo_test
            - run_entries
